DROP TABLE IF EXISTS
    locations,
    event_compilations,
    compilations,
    requests,
    events,
    users,
    event_categories,
    event_locations;

CREATE TABLE IF NOT EXISTS users
(

    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(100)                            NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS event_categories
(

    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS event_locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(

    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title                VARCHAR(120)                            NOT NULL,
    annotation           VARCHAR(2000)                           NOT NULL,
    description          VARCHAR(2000)                           NOT NULL,
    category_id          BIGINT REFERENCES event_categories,
    event_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location_id          BIGINT REFERENCES locations (id),
    initiator_id         BIGINT REFERENCES users,
    is_paid              BOOLEAN                                 NOT NULL,
    participant_limit    INT                                     NOT NULL,
    is_request_moderated BOOLEAN                                 NOT NULL,
    creation_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    publication_date     TIMESTAMP WITHOUT TIME ZONE,
    state                VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id     BIGINT                                  NOT NULL references events on delete cascade,
    requestor_id BIGINT                                  NOT NULL references users on delete cascade,
    status       VARCHAR(100)                            NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    event_id       BIGINT NOT NULL references events (id) on delete cascade,
    compilation_id BIGINT NOT NULL references compilations (id) on delete cascade,
    primary key (event_id, compilation_id)
);
